### ISSUE TITLE
Provide "Hide regional content" checkbox on country page's search?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_solr#132]
Raised by @jpeizer1 

Perhaps the solution would be to clearly identify ODM returned data in the search and provide a filter in the country search screens to filter ODM data out. 

![mockup](https://user-images.githubusercontent.com/384894/27325234-095956ec-55a8-11e7-9a61-a7a70b9562ed.png)

In this mockup, if users check the _hide regional content_ box, then only the myanmar contents will be shown, meaning that the other Land resources related to other countries (vietnam, cambodia, Laos, Thailand) would be hidden.

@thetaung2 @DragonVirus @Huyeng @ChandaraKhun how do you like this idea to solve https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/128 ?

**Comment by jpeizer1** [comment]
I think this is best.... There is an issue of input and output... without such an indicator *ANY* country site that has an issue with ODM data showing up in their search, whether because of translation issues, relevance, etc.. can actually create a situation where data is not published on *ODM* pending dealing with the situation editorially on the other country site. With such an indicator, users are is control of seeing or not seeing the regional data -- which means you are dealing with it as an output issue that doesn't necessarily stop publishing on ODM or create the necessity for a whole new bunch of editorial rules. Maybe a country can choose to make HIDE the ODM data as the search default...

Rachel raised another related  issue about wanting data from every country related to a second country showing up on that second country's search. That raises editorial responsibility between country site issues as well as language issues and duplicate issues. Logically however, any country record that referenced another country would show up on the regional ODM site in English as a regional issues because it involves more than one country. You therefore don't need to pick up searches of each country site, just the ODM site to  include such information... THAT MEANS if you have this hide/show ODM filter option in search you have complete control of the process without dealing with the trickier editorial issues of picking up data between country sites. Issues of regional import are supposed to show up on the ODM site in English --  they will therefore be picked up by any country site they have relevance to, unless the user in that country decides on their own they wish to filter them out because of their own conception of relevance of this data.

**Comment by acorbi** [comment]
this has been address by adding the **Show regional contents on results** option on the plugin's setting
