### ISSUE TITLE
Latest improvements on Search page to review

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_solr#140]
Dear @OpenDevelopmentMekong/core @OpenDevelopmentMekong/tech @OpenDevelopmentMekong/editorial,

After reviewing the feedback provided by David Hindley and the team in regard to the search page tests conducted last week, I have made following improvements/changes that I would like you to kindly review and test:

Changes have been already deployed on PP and can be tested on both ODM and country sites.

### Implemented View All tab/section

This one was one of the main points raised by testers and needs not much clarification. Now the search page shows results from all content types per default. Example: https://pp.opendevelopmentmekong.net/?s=land

![screenshot from 2017-06-20 20-12-25](https://user-images.githubusercontent.com/384894/27348581-df3fb14c-55f4-11e7-8615-446eb16ec447.png)
![screenshot from 2017-06-20 20-12-49](https://user-images.githubusercontent.com/384894/27348587-e1dab91a-55f4-11e7-8916-708a2ae31c7e.png)

### Implemented auto-complete suggestions

When the user types some characters on the search, the page provides suggestions out of the titles currently stored on the search index.

Example: Type "floo" (or something else which is longer than 3 chars) and wait a bit, suggestions would then appear below the search bar.

![screenshot from 2017-06-20 19-39-36](https://user-images.githubusercontent.com/384894/27348597-ea5fc24c-55f4-11e7-9888-631ef5fc8812.png)

### Implemented suggestions in case of misspellings

If the user types a search term which contains typos/misspellings and in case the search engine considers them as such, the page will show a message "Did you mean?" and provide suggestions which should lead to results.

Example: https://pp.opendevelopmentmekong.net/?s=forestt
Example: https://pp.opendevelopmentcambodia.net/?s=forestt

![screenshot from 2017-06-20 20-13-53](https://user-images.githubusercontent.com/384894/27348623-079197dc-55f5-11e7-87b4-4c213f581ca2.png)
![screenshot from 2017-06-20 20-14-03](https://user-images.githubusercontent.com/384894/27348624-07b56b12-55f5-11e7-9e99-4e78aa0bae43.png)

**Comment by ChandaraKhun** [comment]
**Implemented View All tab/section**
Inconsistent figures of the total number of resources on the website (Search page) and Wordpress back-end:
  - News (Published): Website (Search Page)=22,174 vs. Wordpress Back-End=22,596  
    (Around 422 news summaries were missing).
![screenshot_3](https://user-images.githubusercontent.com/10953792/27367805-1b014036-5679-11e7-977d-757689e6998f.jpg)

Inconsistent figures of the total number of records in All, and total calculation of all content type: 
  - Land: All=4883; total calculation: 4881 (excluding Site Updates?)
  - Forest: All=1556; total calculation: 1553 (excluding Site Updates?)
**Implemented auto-complete suggestions**
- pop-up of the words is not behaving/presenting in order of the number of words (from one word to two/more words): Give “two characters” (without any space) were typed into the Text search box, then auto-complete suggestions shall show “a word” but not two/more words. 
Example: “fo" was typed, then the suggestion shall be “forest", “forestry", “fog" … but not a long title of the records. 
- pop-up words shall be the “closest” or the “most relevant” to the characters users did type. In the case, the auto-complete suggestions are not effective since the results are not than necessary, if the tile of each record is shown as suggested “options". 
**Note on editorial issues**: 
-The show-up of resources from other OD organization in their local language. Example, when users type “hazard", suggested words appear in Vietnamese. 
-Error with Eng/Khmer. Ex, type the word “forest" ===> “[:en] Forest Cover [:km] គម្របព្រៃ]”

**Implemented suggestions in case of misspelling**
Generally it works pretty well, since the search results are exported from:

- The related and unfinished words: example, Hu Sen; manipul The results show Hu & Hun Sen, manipulate/manipulation;
- Limited effectiveness: because 
  - Generally, it work pretty well for one word but not two/more words. Example, when users typed “developement projets” ===> Did you mean “project"? (Omitting “development"). However, it is good to have auto-correction of the misspelling by underlining those words in “red" and suggested correct words (the present function). 
  - Limited number of auto-suggested words. Example, Deconcentralization ===> Did you mean “decentralization"?  (Not others: deconcentration, decentralization)

**Comment by ChandaraKhun** [comment]
![screenshot_4](https://user-images.githubusercontent.com/10953792/27367956-fa042528-5679-11e7-8ab8-92fc96d00006.jpg)

Solutions: Show the following words
-Key words (in metadata field)
-Tags (news/announcement)
-Category
-Words from the breakdown of the record title
-Popular words (after compilation and review)
-Words in story of the search page/search engine on desktop/devices …

**Comment by acorbi** [comment]
Thanks @ChandaraKhun for your feedback. I will do some improvements today.

**Comment by acorbi** [comment]
@ChandaraKhun let me reply to your feedback here:

> News (Published): Website (Search Page)=22,174 vs. Wordpress Back-End=22,596
(Around 422 news summaries were missing).

The appropiate figure is **22,174** vs. **22,210** (only published items are indexed on the seach). That means that there are 36 news articles not being indexed. Need to investigate why but this does not seem so critical, other content types are completely indexed: 132 Topics, 155 Map layers, 34 profiles, 296 announcements.

> pop-up of the words is not behaving/presenting in order of the number of words (from one word to two/more words): Give “two characters” (without any space) were typed into the Text search box, then auto-complete suggestions shall show “a word” but not two/more words.
Example: “fo" was typed, then the suggestion shall be “forest", “forestry", “fog" … but not a long title of the records.

Let me elaborate on the current implementation:

I decided to use the spellchecking mechanisms in 2 ways: 

1. in order to provide the _did you mean?_ functionality in case the search engine detects that there is some misspelling (described more in detail below).

2. In order to provide suggestions to existing contents directly on the search bar so the user can navigate directly to it incase it finds the corresponding title on the list of suggestions. This is how it was initially conceived, see mockup:

![search_autocomplete](https://user-images.githubusercontent.com/384894/27391866-5c040222-56a5-11e7-9ec1-76ca6fa8d18c.jpg)

What you are suggesting with your comment is that the search bar should provide suggestions to the words typed by the user, word by word. correct? This other option is technically possible but I believe it overlaps with the functionality of the _did you mean?_ suggestions and therefore I would advocate to leave it as it is now.

@Huyeng @prustar @gimmemochi @DBishton @thetaung2 @DragonVirus What is your preference in this regard?

FYI: I have improved the logic so now only contents available for the **current country** (cambodia in case of ODC, Vietnam in case of ODV, etc...) and the **current language** are shown. That means that now, no vietnamese suggestions should appear when users are on ODC.

> Limited effectiveness: because Generally, it work pretty well for one word but not two/more words. Example, when users typed “developement projets” ===> Did you mean “project"? (Omitting “development"). However, it is good to have auto-correction of the misspelling by underlining those words in “red" and suggested correct words (the present function). Limited number of auto-suggested words. Example, Deconcentralization ===> Did you mean “decentralization"? (Not others: deconcentration, decentralization)

As you suggested, I have improved the _did you mean?_ functionality so it provides the complete sentence (including those words that are correct) and lists up to 3 suggestions:

![screenshot from 2017-06-21 18-12-12](https://user-images.githubusercontent.com/384894/27394698-667895e4-56ad-11e7-8ef4-d071ce901a05.png)
![screenshot from 2017-06-21 18-12-51](https://user-images.githubusercontent.com/384894/27394699-667dd6b2-56ad-11e7-83d6-c787e02dc3a6.png)

https://pp.opendevelopmentmekong.net/?type=all&taxonomy=all&sorting=score&s=development+projets
https://pp.opendevelopmentcambodia.net/km/?type=&s=developement+projets&taxonomy=all&metadata_created=all&sorting=score

**Comment by acorbi** [comment]
A quick update. Today I have introduced another change on the logic of the search which applies for country sites. This change consist on **exposing only results in english or the local language** on the search page of a country site.

With this, one of the issues recently raised ( a vietnamese dataset appearing on ODC's search) has been fixed.

@ChandaraKhun @Huyeng @tthy @prustar @gimmemochi @DBishton are we good to release the current code on PP into PROD? Or are there any other issues that you might want to see fixed before doing this?

Please note that there are some related issues still being reproduced on PROD that can be fixed only once the code is released, see https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1031

**Comment by acorbi** [comment]
Another quick update.

I have just implemented a mechanism which assigns more weight to following content types:

- datasets
- library publications
- laws
- agreements
- topics
- map layers
-profiles

This mechanism can be adapted so the weighting event is increased of reduced. I have done some tests and news articles are still appearing on the first page of results when they match the search criteria specified ( entered term is either a keyword or topic on the news article, etc...)

**Comment by gimmemochi** [comment]
>What is your preference in this regard? Suggest titles directly or suggest words?
>
@acorbi My preference is word suggestions. Can we add the spellcheck dotted line as well? See image. We are used to this in text messages and word processing program. Shouldn't be a new thing to folks. 
![guid-b2d6ad9d-2323-4b50-8324-466c1c19ab74](https://user-images.githubusercontent.com/6489398/27614698-fd6c2410-5b68-11e7-845c-88ecf11eeb81.png)

**Comment by acorbi** [comment]
@Huyeng Just for the record I am linking this issue https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/161 here where you are indicating your preference for word-by-word suggestions as @gimmemochi didi

**Comment by acorbi** [comment]
Latest code has been deployed into PROD, this issue will be closed now. Please raise individual issues if there are related or outstanding tasks
